---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: latest

inputs:
  - name: boot-concourse

run:
  path: "boot-concourse/gradlew"
  args: ["--build-file", "boot-concourse/build.gradle", "assemble", "cfLogin", "cfPush"]

params:
  TERM: -dumb
  GRADLE_OPTS: -Dorg.gradle.native=false
