---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: anapsix/alpine-java
    #repository: java
    #tag: openjdk-8-alpine
    tag: 8_jdk

inputs:
  - name: boot-concourse

run:
  path: "touch ~/.gradle/gradle.properties && echo 'cfUsername={{cf-username}} \ncfPassword={{cf-password}}' >> ~/.gradle/gradle.properties"

run:
  path: "boot-concourse/gradlew"
  args: ["--build-file", "boot-concourse/build.gradle", "assemble", "cfLogin", "cfPush", "-Dusername={{cf-username}}", "-Dpassword={{cf-password}}"]

params:
  TERM: -dumb
  GRADLE_OPTS: -Dorg.gradle.native=false
