---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine-bash
    #repository: java
    #tag: openjdk-8-alpine
    tag: latest

inputs:
  - name: boot-concourse

run:
  path: "boot-concourse/gradlew"
  args: ["--build-file", "boot-concourse/build.gradle", "assemble", "cfLogin", "cfPush", "-Du", "${cf-username}", "-Dp", "${cf-password}"]

params:
  TERM: -dumb
  GRADLE_OPTS: -Dorg.gradle.native=false
