---
resources:
  - name: boot-concourse
    type: git
    source:
      uri: https://github.com/ravis-git/boot-concourse.git
      branch: master

jobs:
  - name: build-test
    plan:
    - get: boot-concourse
      trigger: true
    - task: package
      privileged: true
      file: source-code/ci/tasks/build.yml